server.port: ${HTTP_PORT:8080}
infobip:
  api-host: ${INFOBIP_API_HOST:api.infobip.com}
  rtc-token-path: ${INFOBIP_RTC_TOKEN_PATH:/webrtc/1/token}
  api-key: '1beaa9fe72bc086dfbe0c15ce43c0689-5386a790-2b57-4ace-b657-e95d5d1464fd'
  application-id: '5d6ca3af-771b-4ea8-bce3-35b065f658a9'
